export const SORT = 'SORT';
export const PAGINATION = 'PAGINATION';
export const REQUEST_DATA_BEGIN = 'REQUEST_DATA_BEGIN';
export const REQUEST_DATA_SUCCESS = 'REQUEST_DATA_SUCCESS';
export const REQUEST_DATA_FAILURE = 'REQUEST_DATA_FAILURE';
